### ISSUE TITLE
Link to Livestream series

### ISSUE THREAD

**Issue by NdubuisiJr** [OpesanyaAdebayo/fintech-lite#11]
Hi.

I'm really interested in the live stream and the following up of each concept you will teach. If possible, it will be nice to drop the link to the live stream on the readme file or a link to the recorded sessions.

Thanks

**Comment by orimdominic** [comment]
@NdubuisiJr I found this Youtube video by @OpesanyaAdebayo [2- Building A digital Wallet](https://www.youtube.com/watch?v=lkWdXDfi_xU&list=PLZ8xNq6BKXcAxzGudEshzsnkbTnv3rTUr)

You could make a PR with it

**Comment by OpesanyaAdebayo** [comment]
Closing this since the link has been provided.
